{
 "title": "ib-hca",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "region",
    "query": {
     "query": "label_values(node_ib_counters, region)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_ib_counters{cluster!~\"managersystem\",region=~\"$region\"}, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_ib_counters{cluster!~\"managersystem\",cluster=~\"$cluster\",instance!~\"jqc[0-9]{2}\",instance!~\"jdczt[0-9]{2}\",instance!~\"nfcgd[0-9]{2}\",instance!~\"cepheus-master[0-9]{2}\",instance!~\"nfczs[0-9]{2}\",instance!~\"aquila-s-[0-9]{3}\",namespace=\"monitoring\"}, instance)"
    }
   },
   { "name": "topK", "query": "5,10,15" }
  ]
 },
 "panels": [
  {
   "title": "cluster hca static topk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "集群网卡发送流量topk",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk($topK,rate(node_ib_counters{metricsName=\"port_xmit_data\",cluster=\"$cluster\"}[5m])*4)",
       "legendFormat": "{{instance}} : {{IBDev}}"
      }
     ]
    },
    {
     "title": "集群网卡接收流量topk",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk($topK,rate(node_ib_counters{metricsName=\"port_rcv_data\",cluster=\"$cluster\"}[5m])*4)",
       "legendFormat": "{{instance}} : {{IBDev}}"
      }
     ]
    },
    {
     "title": "集群 QP_num topK",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($topK, node_ib_counters{metricsName=\"QPNum\",cluster=\"$cluster\"})",
       "legendFormat": "{{instance}} : {{IBDev}}"
      }
     ]
    }
   ]
  },
  { "title": "host hca static info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "单台设备网卡发送流量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_ib_counters{metricsName=\"port_xmit_data\",cluster=\"$cluster\",instance=\"$node\"}[5m])*4",
     "legendFormat": "{{instance}} : {{IBDev}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "单台设备网卡接收流量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_ib_counters{metricsName=\"port_rcv_data\",cluster=\"$cluster\",instance=\"$node\"}[5m])*4",
     "legendFormat": "{{instance}} : {{IBDev}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "设备QP数目",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_ib_counters{metricsName=\"QPNum\",cluster=\"$cluster\",instance=\"$node\"}",
     "legendFormat": "{{instance}} : {{IBDev}}"
    }
   ]
  },
  {
   "title": "node hca counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "rdma_counter_port_xmit_data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_ib_counters{metricsName=\"port_xmit_data\",cluster=\"$cluster\", instance=~\"$node\"}[5m])*4"
      }
     ]
    },
    {
     "title": "rdma_counter_port_rcv_data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_ib_counters{metricsName=\"port_rcv_data\",cluster=\"$cluster\", instance=~\"$node\"}[5m])*4"
      }
     ]
    },
    {
     "title": "rdma_counter_QP_num",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"QPNum\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_link_downed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"link_downed\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_local_link_integrity_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"local_link_integrity_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_rcv_remote_physical_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_rcv_remote_physical_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_xmit_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_xmit_packets\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_rcv_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_rcv_packets\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_xmit_wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "timeticks" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_xmit_wait\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_VL15_dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"VL15_dropped\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_rcv_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_rcv_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_symbol_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"symbol_error\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_unicast_rcv_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"unicast_rcv_packets\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_unicast_xmit_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"unicast_xmit_packets\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_xmit_discards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_xmit_discards\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_rcv_switch_relay_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_rcv_switch_relay_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_rcv_constraint_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_rcv_constraint_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_excessive_buffer_overrun_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"excessive_buffer_overrun_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_multicast_rcv_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"multicast_rcv_packets\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_multicast_xmit_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"multicast_xmit_packets\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_link_error_recovery",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"link_error_recovery\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_port_xmit_constraint_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"port_xmit_constraint_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_QP_num_rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(node_ib_counters{metricsName=\"QPNum\",cluster=\"$cluster\", instance=~\"$node\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "node hca hw counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "rdma_counter_hw_duplicate_request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"duplicate_request\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_duplicate_request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"duplicate_request\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_lifespan",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"lifespan\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_local_ack_timeout_err",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"local_ack_timeout_err\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_out_of_buffer ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"out_of_buffer\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_out_of_sequence",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"out_of_sequence\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_packet_seq_err",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"packet_seq_err\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_packet_seq_err",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"packet_seq_err\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_req_cqe_flush_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"req_cqe_flush_error\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_req_remote_access_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"req_remote_access_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_req_remote_invalid_request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"req_remote_invalid_request\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_resp_cqe_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"resp_cqe_error\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_resp_cqe_flush_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"resp_cqe_flush_error\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_resp_local_length_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"resp_local_length_error\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_resp_local_length_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"resp_local_length_error\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_resp_remote_access_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"resp_remote_access_errors\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_rnr_nak_retry_err",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"rnr_nak_retry_err\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_roce_adp_retrans",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"roce_adp_retrans\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_roce_adp_retrans_to ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"roce_adp_retrans_to\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_roce_slow_restart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"roce_slow_restart\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_roce_slow_restart_cnps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"roce_slow_restart_cnps\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_roce_slow_restart_trans",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"roce_slow_restart_trans\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_rx_atomic_requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"rx_atomic_requests\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_rx_dct_connect",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"rx_dct_connect\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_rx_icrc_encapsulated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"rx_icrc_encapsulated\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_rx_read_requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"rx_read_requests\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "rdma_counter_hw_rx_write_requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "node_ib_counters{metricsName=\"rx_write_requests\",cluster=\"$cluster\", instance=~\"$node\"}"
      }
     ]
    }
   ]
  }
 ]
}